services:
  - type: web
    name: project-lead-scheduler
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: "*"
    healthCheckPath: /api/health
    autoDeploy: true
